piVersion: v1
clusters:
  - cluster:
      certificate-authority: /Users/zhaojiaming/.minikube/ca.crt
      extensions:
        - extension:
            last-update: Thu, 22 Sep 2022 13:56:04 CST
            provider: minikube.sigs.k8s.io
            version: v1.25.2
          name: cluster_info
      server: https://127.0.0.1:53552
    name: minikube
contexts:
  - context:
      cluster: minikube
      extensions:
        - extension:
            last-update: Thu, 22 Sep 2022 13:56:04 CST
            provider: minikube.sigs.k8s.io
            version: v1.25.2
          name: context_info
      namespace: default
      user: minikube
    name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
  - name: minikube
    user:
      client-certificate: /Users/zhaojiaming/.minikube/profiles/minikube/client.crt
      client-key: /Users/zhaojiaming/.minikube/profiles/minikube/client.key