apiVersion: v1
kind: Pod
metadata:
  name: test
  namespace: default
spec:
  containers:
    - env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              key: db-user
              name: test-secret
        - name: DB_PWD
          valueFrom:
            secretKeyRef:
              key: db-password
              name: test-secret
      image: ccr.ccs.tencentyun.com/kugo/demo:v5
      imagePullPolicy: Always
      name: test-k8s