apiVersion: v1
kind: Service
metadata:
  name: test-service
spec:
  ports:
    - name: http-port
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001
  selector:
    app: test-deployment
  type: NodePort